### ISSUE TITLE
 "_OBJC_CLASS_$_SDWeiXinPhotoContainerView", referenced from:

### ISSUE THREAD

**Issue by MansionWayh** [andy123234/Moment-Base-YYKit-#3]
"_OBJC_CLASS_$_SDWeiXinPhotoContainerView", referenced from: 报错。。。。不知道什么原因
![2018-01-29 3 19 49](https://user-images.githubusercontent.com/16216828/35498138-0c8d777a-0508-11e8-98b7-9eb71b5a32d6.png)

**Comment by andy123234** [comment]
看看工程中 Build Phases - Compile Sources 里是不是缺少SDWeiXinPhotoContainerView.m文件,如果没有就手动添加上,或者重新下载工程也可以.
