### ISSUE TITLE
单击用户评论以后,怎么不能进行评论呢

### ISSUE THREAD

**Issue by DongfengWang123** [andy123234/Moment-Base-YYKit-#5]

**Comment by andy123234** [comment]
在NewDynamicsTableViewCell.h里有声明
-(void)DynamicsCell:(NewDynamicsTableViewCell *)cell didClickComment:(DynamicsCommentItemModel *)commentModel;
这个方法就是响应点击其它用户评论时的代理方法.在controller实现以后写上想要的操作就可以了.
